-- Converted from cengi_cursos.sql (MariaDB/MySQL) to PostgreSQL for Supabase.
-- Generated for project cengicursos.

begin;

set check_function_bodies = off;

drop table if exists public.asistencia cascade;
drop table if exists public.control_cursos cascade;
drop table if exists public.asignaciones_import cascade;
drop table if exists public.asignaciones cascade;
drop table if exists public.participantes_import cascade;
drop table if exists public.participantes cascade;
drop table if exists public.solicitudes_inscripcion cascade;
drop table if exists public.users cascade;
drop table if exists public.cursos cascade;
drop table if exists public.categorias_cursos cascade;
drop table if exists public.grado_academico cascade;
drop table if exists public.ingenios cascade;

drop type if exists public.jornada_cursos_enum cascade;
drop type if exists public.tipo_capacitacion_enum cascade;
drop type if exists public.tipo_pago_enum cascade;
drop type if exists public.estado_solicitud_enum cascade;
drop type if exists public.rol_usuario_enum cascade;

create type public.jornada_cursos_enum as enum ('Matutina', 'Vespertina', 'Todo Completo');
create type public.tipo_capacitacion_enum as enum ('Curso', 'Diplomado', 'Seminario');
create type public.tipo_pago_enum as enum ('Ingenio', 'Propio');
create type public.estado_solicitud_enum as enum ('Pendiente', 'Aprobado', 'Rechazado');
create type public.rol_usuario_enum as enum ('Administrador', 'Delegado');

create table public.ingenios (
  id integer generated by default as identity primary key,
  nombre_ingenios varchar(255) not null,
  creado timestamptz,
  actualizado timestamptz
);

create table public.categorias_cursos (
  id integer generated by default as identity primary key,
  descripcion_categorias_cursos varchar(255) not null,
  estado_categorias_cursos integer not null default 1,
  creado timestamptz,
  actualizado timestamptz default now()
);

create table public.grado_academico (
  id integer generated by default as identity primary key,
  nombre_grado varchar(255) not null,
  creado timestamptz default now()
);

create table public.cursos (
  id integer generated by default as identity primary key,
  categoria_curso_id integer not null references public.categorias_cursos(id),
  ingenio_id integer not null references public.ingenios(id),
  nombre_cursos varchar(255) not null,
  jornada_cursos public.jornada_cursos_enum not null,
  dias varchar(255) not null,
  horario varchar(255) not null,
  inicio date,
  fin date,
  creado timestamptz,
  actualizado timestamptz default now(),
  tipo public.tipo_capacitacion_enum not null default 'Curso'
);

create table public.participantes (
  id integer generated by default as identity primary key,
  ingenio_id integer not null references public.ingenios(id),
  usuarios_id integer not null,
  cui_participantes varchar(25),
  nombre_participantes varchar(255) not null,
  puesto_participantes varchar(255) not null,
  area_participantes varchar(255) not null,
  estado_participantes integer not null default 1,
  creado timestamptz,
  actualizado timestamptz default now(),
  constraint participantes_cui_participantes_unique unique (cui_participantes)
);

create table public.participantes_import (
  id integer generated by default as identity primary key,
  ingenio_id integer not null references public.ingenios(id),
  usuarios_id integer not null,
  cui_participantes varchar(25),
  nombre_participantes varchar(255) not null,
  puesto_participantes varchar(255) not null,
  area_participantes varchar(255) not null,
  estado_participantes integer not null default 1,
  creado timestamptz,
  actualizado timestamptz not null default now(),
  constraint participantes_import_cui_participantes_unique unique (cui_participantes)
);

create table public.users (
  id integer generated by default as identity primary key,
  nombre varchar(191) not null,
  email varchar(191) not null,
  password varchar(191) not null,
  ingenio_id integer not null default 2 references public.ingenios(id) on update cascade,
  rol public.rol_usuario_enum not null default 'Delegado',
  creado timestamptz,
  actualizado timestamptz,
  constraint usuarios_email_unique unique (email)
);

create table public.asignaciones (
  id integer generated by default as identity primary key,
  participantes_id integer not null references public.participantes(id),
  usuarios_id integer not null references public.users(id),
  cursos_id integer not null references public.cursos(id),
  estado_asignaciones integer not null default 1,
  creado timestamptz,
  actualizado timestamptz default now(),
  constraint particip_curso unique (participantes_id, cursos_id)
);

create table public.asignaciones_import (
  id integer,
  participantes_id integer not null,
  usuarios_id integer not null,
  cursos_id integer not null,
  estado_asignaciones integer not null default 1,
  creado timestamptz,
  actualizado timestamptz default now()
);

create table public.asistencia (
  id_asistencia bigint generated by default as identity primary key,
  id_asignacion integer references public.asignaciones(id) on delete cascade on update cascade,
  fecha date
);

create table public.control_cursos (
  id_control integer generated by default as identity primary key,
  asignacion_id integer not null references public.asignaciones(id),
  asistencia numeric(5,2) default 0.00,
  evaluacion numeric(5,2) default 0.00,
  posevaluacion numeric(5,2) default 0.00,
  diploma varchar(255),
  creado timestamptz default now(),
  actualizado timestamptz default now()
);

create table public.solicitudes_inscripcion (
  id_solicitud integer generated by default as identity primary key,
  nombre_participante varchar(255),
  cui_participante varchar(25),
  puesto_participante varchar(255),
  area_participante varchar(255),
  correo varchar(255),
  telefono varchar(20),
  pais varchar(100),
  grado_academico_id integer references public.grado_academico(id),
  ha_participado_antes boolean default false,
  cursos_participados text,
  como_se_entero varchar(255),
  ingenio_id integer references public.ingenios(id),
  otro_ingenio varchar(255),
  curso_id integer references public.cursos(id),
  tipo_pago public.tipo_pago_enum,
  estado public.estado_solicitud_enum default 'Pendiente',
  fecha_solicitud timestamptz not null default now()
);

create index asignaciones_participantes_id_idx on public.asignaciones(participantes_id);
create index asignaciones_usuarios_id_idx on public.asignaciones(usuarios_id);
create index asignaciones_cursos_id_idx on public.asignaciones(cursos_id);
create index asignaciones_import_participantes_id_idx on public.asignaciones_import(participantes_id);
create index asignaciones_import_usuarios_id_idx on public.asignaciones_import(usuarios_id);
create index asignaciones_import_cursos_id_idx on public.asignaciones_import(cursos_id);
create index asistencia_id_asignacion_idx on public.asistencia(id_asignacion);
create index control_cursos_asignacion_id_idx on public.control_cursos(asignacion_id);
create index cursos_categoria_curso_id_idx on public.cursos(categoria_curso_id);
create index cursos_ingenio_id_idx on public.cursos(ingenio_id);
create index solicitudes_inscripcion_grado_academico_id_idx on public.solicitudes_inscripcion(grado_academico_id);
create index participantes_cui_participantes_idx on public.participantes(cui_participantes);
create index participantes_ingenio_id_idx on public.participantes(ingenio_id);
create index participantes_import_cui_participantes_idx on public.participantes_import(cui_participantes);
create index participantes_import_ingenio_id_idx on public.participantes_import(ingenio_id);
create index solicitudes_inscripcion_ingenio_id_idx on public.solicitudes_inscripcion(ingenio_id);
create index solicitudes_inscripcion_curso_id_idx on public.solicitudes_inscripcion(curso_id);
create index solicitudes_inscripcion_fecha_idx on public.solicitudes_inscripcion(fecha_solicitud desc);
create index users_ingenio_id_idx on public.users(ingenio_id);

select setval(pg_get_serial_sequence('public.ingenios', 'id'), coalesce((select max(id) from public.ingenios), 1), true);
select setval(pg_get_serial_sequence('public.categorias_cursos', 'id'), coalesce((select max(id) from public.categorias_cursos), 1), true);
insert into public.grado_academico (id, nombre_grado, creado) values
  (1, 'Licenciatura', now()),
  (2, 'Ingeniería', now()),
  (3, 'Estudios Universitarios', now()),
  (4, 'Diversificado', now()),
  (5, 'Otros', now())
on conflict (id) do update set nombre_grado = excluded.nombre_grado;
select setval(pg_get_serial_sequence('public.grado_academico', 'id'), coalesce((select max(id) from public.grado_academico), 1), true);
select setval(pg_get_serial_sequence('public.cursos', 'id'), coalesce((select max(id) from public.cursos), 1), true);
select setval(pg_get_serial_sequence('public.participantes', 'id'), coalesce((select max(id) from public.participantes), 1), true);
select setval(pg_get_serial_sequence('public.participantes_import', 'id'), coalesce((select max(id) from public.participantes_import), 1), true);
select setval(pg_get_serial_sequence('public.users', 'id'), coalesce((select max(id) from public.users), 1), true);
select setval(pg_get_serial_sequence('public.asignaciones', 'id'), coalesce((select max(id) from public.asignaciones), 1), true);
select setval(pg_get_serial_sequence('public.asistencia', 'id_asistencia'), coalesce((select max(id_asistencia) from public.asistencia), 1), true);
select setval(pg_get_serial_sequence('public.control_cursos', 'id_control'), coalesce((select max(id_control) from public.control_cursos), 1), true);
select setval(pg_get_serial_sequence('public.solicitudes_inscripcion', 'id_solicitud'), coalesce((select max(id_solicitud) from public.solicitudes_inscripcion), 1), true);

alter table public.ingenios enable row level security;
alter table public.categorias_cursos enable row level security;
alter table public.grado_academico enable row level security;
alter table public.cursos enable row level security;
alter table public.participantes enable row level security;
alter table public.participantes_import enable row level security;
alter table public.users enable row level security;
alter table public.asignaciones enable row level security;
alter table public.asignaciones_import enable row level security;
alter table public.asistencia enable row level security;
alter table public.control_cursos enable row level security;
alter table public.solicitudes_inscripcion enable row level security;

create policy "lectura publica ingenios" on public.ingenios for select to anon, authenticated using (true);
create policy "lectura publica grado academico" on public.grado_academico for select to anon, authenticated using (true);
create policy "lectura publica cursos" on public.cursos for select to anon, authenticated using (true);
create policy "lectura publica solicitudes" on public.solicitudes_inscripcion for select to anon, authenticated using (true);
create policy "insert publico solicitudes" on public.solicitudes_inscripcion for insert to anon, authenticated with check (true);

grant usage on schema public to anon, authenticated, service_role;
revoke all on all tables in schema public from anon, authenticated;
grant select on public.ingenios to anon, authenticated, service_role;
grant select on public.categorias_cursos to anon, authenticated, service_role;
grant select on public.grado_academico to anon, authenticated, service_role;
grant select on public.cursos to anon, authenticated, service_role;
grant select, insert on public.solicitudes_inscripcion to anon, authenticated, service_role;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

commit;
